# vim:sw=2:ts=2:et:set filetype=yaml :

services:
  data_vol:
    image: ghcr.io/andreluis933/setup-vps-data_vol:latest
    pull_policy: always
    container_name: data_vol
    hostname: data_vol
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    volumes:
      - data:/data:rw
      - scripts:/data/scripts:rw
      - webhook_jobs:/data/webhook_jobs:rw
      - nginx:/data/nginx:rw
      - letsencrypt:/data/letsencrypt:rw
      - certbot:/data/certbot:rw
    networks:
      nginx_network:

  dockerlabs:
    pull_policy: always
    image: ghcr.io/andreluis933/setup-vps-dockerlabs:latest
    restart: unless-stopped
    volumes:
      - scripts:/scripts:ro
      - webhook_jobs:/app/webhook_jobs:rw
    env_file:
      - .env
    environment:
      - GIN_MODE=release
    healthcheck:
      test: ['CMD-SHELL', 'wget --no-verbose --tries=1 --spider http://localhost:8000/health || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    depends_on:
      data_vol:
        condition: service_started
    networks:
      nginx_network:

  nginx:
    container_name: nginx
    hostname: nginx
    pull_policy: always
    image: ghcr.io/andreluis933/setup-vps-nginx:latest
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    env_file:
      - .env
    volumes:
      - scripts:/scripts:ro
      - nginx:/etc/nginx:ro
      - letsencrypt:/etc/letsencrypt:ro
      - certbot:/var/www/certbot:rw
    depends_on:
      data_vol:
        condition: service_started
    networks:
      - nginx_network

  certbot:
    container_name: certbot
    hostname: certbot
    pull_policy: always
    image: ghcr.io/andreluis933/setup-vps-certbot:latest
    restart: unless-stopped
    volumes:
      - scripts:/scripts:ro
      - letsencrypt:/etc/letsencrypt:rw
      - certbot:/var/www/certbot:rw
    entrypoint: /scripts/certbot_renewal
    networks:
      - nginx_network
    depends_on:
      data_vol:
        condition: service_started

networks:
  nginx_network:
    ipam:
      driver: default
      config:
        - subnet: '10.11.12.0/24'

volumes:
  data:
  scripts:
  webhook_jobs:
  nginx:
  certbot:
  letsencrypt:
